[package]
name = "fs-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.84.2", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
